const fs = require('fs');
const path = require('path');

const questionsPath = path.join(__dirname, 'src/data/questions.json');
const rawData = fs.readFileSync(questionsPath, 'utf8');
const questions = JSON.parse(rawData);

let currentId = Math.max(...questions.map(q => q.id), 0) + 1;

const newQuestions = [
    // ①呼吸器手技 (Series of 70+ items)
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "吸引", "question": "気管吸引時にカテーテルを「引き抜きながら」回転させる目的はどれか。", "options": ["カテーテルを掃除するため", "一箇所の粘膜を長時間吸引して損傷させないようにしつつ、全周の痰を除去するため", "患者を楽しませるため", "特になし"], "correctAnswerIndex": 1, "explanation": "局所的な陰圧の集中による粘膜損傷（出血や潰瘍）を防ぎ、効率よく痰を巻き取るための必須技術です。", "evidence": "安全な吸引の基本手技", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "酸素療法", "question": "高圧酸素ボンベの主バルブを「全開にした後、半回転戻す」理由は何か。", "options": ["火を小さくするため", "バルブの固着を防ぎ、緊急時に誰でもすぐに締められるように（開閉方向を識別可能に）するため", "ガスを節約するため", "特に意味はない"], "correctAnswerIndex": 1, "explanation": "全開のまま固まると、閉まっているのか開いているのか分からず、事故の際の遮断が遅れるリスクがあります。", "evidence": "高圧ガスタンクの安全取扱い", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "人工呼吸器", "question": "人工呼吸器の「吸気トリガー」感度を「敏感（小さく）」にしすぎた際のリスクはどれか。", "options": ["呼吸が止まる", "わずかな回路の揺れ等で機械が自発呼吸と誤認して換気してしまう（オートトリガー）", "アラームが鳴らなくなる", "不眠"], "correctAnswerIndex": 1, "explanation": "患者の努力に関係なく機械が勝手に動いてしまい、ファイティングや過換気の原因となります。", "evidence": "呼吸器設定の最適化", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "救急対応", "question": "心肺蘇生中、胸骨圧迫を中断して良い最大時間は何秒以内か。", "options": ["1秒", "10秒以内", "30秒", "中断してはいけない"], "correctAnswerIndex": 1, "explanation": "中断が長くなると脳への灌流圧が急落するため、人工呼吸や解析の際も最小限（10秒以内）に留めます。", "evidence": "CPRの質と生存率の関係", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "モニタリング", "question": "「パルスオキシメータ」を足の指（手指以外）で測る際の注意点はどれか。", "options": ["精度が格段に上がる", "足は末梢血管の収縮（冷え）の影響を受けやすく、数値が低めに出たり不安定になりやすい", "靴下の上から測る", "特にない"], "correctAnswerIndex": 1, "explanation": "血流状態が悪い場合は、なるべく中枢に近い部位や、温めた部位を選択する必要があります。", "evidence": "生体情報モニタの誤差要因", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "口腔ケア", "question": "経口挿管患者の口腔ケア後、顔を「横向き」にするポジショニングの目的（VAP予防以外）はどれか。", "options": ["風景を見せるため", "唾液が重力で口角から外に排出されやすくし、気管への垂れ込みを物理的に防ぐため", "髪型を維持するため", "お腹を休めるため"], "correctAnswerIndex": 1, "explanation": "適切なポジショニングは、ケアの効果を持続させ、合併症リスクを下げる重要な看護介入です。", "evidence": "人工呼吸器関連肺炎(VAP)予防バンドル", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "ドレーン管理", "question": "胸腔ドレーンのドレナージバッグ内に「血液が凝固（固まる）」しているのを発見した際の対応はどれか。", "options": ["そのまま放置する", "ミルキング（しごき）を行い、回路の閉塞を解除して疎通性を確保する", "チューブを切る", "お湯をかける"], "correctAnswerIndex": 1, "explanation": "回路が詰まると胸腔内に排液が溜まり、最悪の場合、心臓を圧迫するため疎通性の維持が極めて重要です。", "evidence": "ドレーンの安全管理：ミルキングの適応", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "その他", "question": "バイタルサインの「血圧」測定時、マンシェット（カフ）を巻く位置の高さはどうあるべきか。", "options": ["頭の高さ", "心臓の高さ（右心房の高さ）", "足の高さ", "どこでも良い"], "correctAnswerIndex": 1, "explanation": "心臓との高さの差により、水柱圧の誤差（約0.8mmHg/cm）が生じるため、正確な測定には位置合わせが必要です。", "evidence": "標準的な血圧測定法", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "吸引", "question": "「気管カニューレ」から多量の鮮血が吸引された際、真っ先に疑うべき生命に危険な合併症はどれか。", "options": ["鼻炎", "無名動脈瘻（むめいどうみゃくろう：チューブが血管を突き破る）", "歯肉炎", "口内の傷"], "correctAnswerIndex": 1, "explanation": "緊急手術を要する致命的な出血であり、即座の救急コールとカフによる一時的な圧迫止血が必要です。", "evidence": "気管切開の重大合併症：無名動脈瘻", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "酸素療法", "question": "「酸素濃縮器」を自宅で使用している患者への停電対策として、必ず備えておくべき物品はどれか。", "options": ["懐中電灯だけ", "予備の携帯用酸素ボンベ", "水", "お菓子"], "correctAnswerIndex": 1, "explanation": "濃縮器は電気で動くため、停電時は止まります。生命維持に必要な酸素を切らさないための予備ボンベは必須です。", "evidence": "在宅酸素療法の安全管理（災害対策）", "reference": "SafetyPlus" },

    // ②疾患観察 (Series of 70+ items)
    { "id": currentId++, "category": "②疾患観察", "subCategory": "心不全", "question": "「BNP（脳性ナトリウム利尿ペプチド）」の数値が上昇している場合にアセスメントできるのはどれか。", "options": ["栄養状態が良い", "心臓に負荷がかかり、心不全が悪化している可能性", "血糖値が高い", "骨が丈夫"], "correctAnswerIndex": 1, "explanation": "心臓が引き伸ばされた時に出るホルモンで、心不全の重症度や経過を客観的に示す血液データです。", "evidence": "心不全バイオマーカーの解釈", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "肺の聴診で「ヒューヒュー」「ピーピー」と聞こえる高い連続音（笛声音・ウィーズ）の原因はどれか。", "options": ["気道が炎症や痙攣で狭くなっている", "痰が詰まっている", "肺胞が膨らんでいる", "心音が響いている"], "correctAnswerIndex": 0, "explanation": "喘息やCOPDなどで、空気の通り道が極細になっている時に発生する音です。", "evidence": "聴診による異常呼吸音の鑑別", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "COPD", "question": "COPD患者が「風邪を引くと急に動けなくなる（増悪）」事態を防ぐための最も効果的な予防接種はどれか。", "options": ["日本脳炎", "インフルエンザワクチンおよび肺炎球菌ワクチン", "麻疹ワクチン", "てんかんワクチン"], "correctAnswerIndex": 1, "explanation": "感染症による増悪はCOPDの進行を早め、直接の死因にもなりやすいため、ワクチンによる予防が強く推奨されます。", "evidence": "COPD診療ガイドライン：感染予防", "reference": "看護roo!" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "肺炎", "question": "「不顕性誤嚥」による肺炎を疑う初期サインとして適切なのはどれか。", "options": ["食事中のひどいむせ", "夜間の微熱や、なんとなく痰の量が増える、声が湿っている", "食欲増進", "不眠"], "correctAnswerIndex": 1, "explanation": "目に見える「むせ」がないまま唾液などが肺に入ることで、ゆっくりと炎症が進む状態です。", "evidence": "誤嚥性肺炎の早期発見アセスメント", "reference": "看護roo!" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "気胸", "question": "気胸の治療「胸腔ドレナージ」中に、排液バッグが横倒しになってしまった際の最大のリスクはどれか。", "options": ["床が汚れる", "水封機能が失われて外気が胸腔に逆流し、気胸を再発・悪化させる", "音がうるさい", "特になし"], "correctAnswerIndex": 1, "explanation": "逆流防止の「水」の壁が崩れるため、二次的な気胸を招く重大な事故となります。", "evidence": "ドレーンシステムの安全管理", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "疾患管理", "question": "「肺塞栓症」を予防するために、弾性ストッキングのサイズを正しく選ぶべき理由（不適切な時のリスク）はどれか。", "options": ["きつすぎると逆に血流を妨げ、ゆるすぎると予防効果がなくなるため", "色が合わないから", "破れやすいから", "特になし"], "correctAnswerIndex": 0, "explanation": "適切な圧迫だけが血栓予防効果を発揮します。計測と正しい装着、定期的な皮膚観察が看護のポイントです。", "evidence": "血栓予防デバイスの適正使用", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "「頸静脈怒張」を観察する際、患者の体位として最も見えやすい（標準的な）角度はどれか。", "options": ["仰臥位 (フラット)", "45度ヘッドアップ (半坐位)", "起坐位", "側臥位"], "correctAnswerIndex": 1, "explanation": "心臓と首の高さの関係で、右心不全などの圧上昇を最も反映しやすい角度です。", "evidence": "身体診察スキル：頸静脈の観察", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "その他", "question": "ショック状態で「皮膚が冷たく、湿っている」際のアセスメント（原因）はどれか。", "options": ["汗っかき", "交感神経の過緊張による末梢血管収縮と発汗", "部屋の温度設定", "特になし"], "correctAnswerIndex": 1, "explanation": "生体が血圧を保とうと必死に戦っている徴候（代償期）であり、緊急の介入を要します。", "evidence": "ショックの症候学：Cold Shock", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "呼吸介助手技の「圧迫法」を強くやりすぎたことで生じるリスクはどれか。", "options": ["肺が丈夫になる", "肋骨骨折や気胸の誘発・悪化", "筋肉がつく", "不眠"], "correctAnswerIndex": 1, "explanation": "高齢者や骨粗鬆症がある患者では、適度な力加減と常に苦痛の有無を確認することが重要です。", "evidence": "呼吸理学療法の安全性確保", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "疾患管理", "question": "せん妄のリスクを上げる「身体的拘束」の弊害として考えられるのはどれか。", "options": ["患者が落ち着く", "活動制限による心身のストレスが脳の混乱を深め、せん妄をさらに悪化させる", "看護師が楽になる", "特になし"], "correctAnswerIndex": 1, "explanation": "安全確保のためにやむを得ず行う場合も、早期解除と環境調整がせん妄ケアの基本です。", "evidence": "せん妄ケアガイドライン", "reference": "看護roo!" },

    // ③薬剤知識 (Series of 70+ items)
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "吸入薬", "question": "吸入薬デバイス「ブリーズヘラー（ウルティブロ等）」で、正しく吸入できたかを確認する「音」はどれか。", "options": ["カチッという音", "カプセルがカタカタと回転する（鳴る）音", "ピーッという音", "音がしないのが正解"], "correctAnswerIndex": 1, "explanation": "カプセルが回る音がすることで、十分な吸速で薬剤が放出されていると判断できます。", "evidence": "ブリーズヘラーの指導ポイント", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗菌薬", "question": "抗菌薬の副作用「薬疹」が出現した際、看護師が即座に行うべき対応はどれか。", "options": ["塗り薬を塗る", "直ちに点滴を中止し、バイタル確認（血圧・喘鳴等）と医師への報告を行う", "入浴させる", "放置する"], "correctAnswerIndex": 1, "explanation": "皮膚の症状だけでなく、喉の腫れ（窒息）やショックへの急激な移行を警戒する必要があります。", "evidence": "薬剤性過敏症症候群への対応", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗凝固薬", "question": "抗凝固薬を内服中の患者が「怪我（出血）」をした時の止血方法で、特に長く続けるべき動作はどれか。", "options": ["水で洗う", "出血部位をしっかり「圧迫（圧迫止血）」し続ける", "消毒する", "絆創膏を貼って終わり"], "correctAnswerIndex": 1, "explanation": "薬の効果で自然に血が固まる力が弱いため、物理的な圧迫による止血時間が通常より必要です。", "evidence": "抗凝固療法における安全指導", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "ステロイド薬", "question": "ステロイド薬の副作用「脂質異常症・糖尿病」を発症しやすい理由（代謝への影響）はどれか。", "options": ["食べ物が美味しいから", "糖新生（糖を作る反応）を促し、インスリンの働きを抑えてしまうため", "運動不足", "特にない"], "correctAnswerIndex": 1, "explanation": "本来のホルモンとしての役割が過剰になるため、血液中の糖や脂質が増加してしまいます。", "evidence": "ステロイド全身副作用への理解", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "鎮静薬", "question": "がんの痛みに用いられる「モルヒネ」と「痛み止めの飲み薬（ロキソニン等）」を一緒に使う理由は何のためか。", "options": ["薬を減らすため", "作用機序の異なる薬を併用することで、痛みを多角的に、効率よく抑えるため", "適当に混ぜているだけ", "特になし"], "correctAnswerIndex": 1, "explanation": "「マルチモーダル鎮痛」と呼び、医療用麻薬の量を抑えつつ、副作用を少なく除痛する標準的な手法です。", "evidence": "がん疼痛薬物療法ガイドライン", "reference": "看護roo!" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "インスリン", "question": "インスリン注射において、同じ部位（お腹など）の中でも「数センチずつ位置をずらす」必要がある理由は何か。", "options": ["痛みが散漫になるから", "皮膚の硬結（リポハイパートロフィー：脂肪肥大）を予防し、吸収を安定させるため", "覚えやすいから", "特に意味はない"], "correctAnswerIndex": 1, "explanation": "固くなってしまった箇所に打つと薬が全く効かなくなり、重篤な高血糖を招くリスクがあります。", "evidence": "インスリン注射部位の管理", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "吸入薬", "question": "吸入ステロイド薬を「お腹が空いている時」に吸う必要はあるか（食事の影響は）。", "options": ["必ず空腹時に吸う", "食事の影響はほとんどないため、決まった時間に忘れず吸うことが優先される", "食中毒の時は吸わない", "特に決まっていない"], "correctAnswerIndex": 1, "explanation": "血中濃度を一定に保つための定期的な吸入が最も重要であり、食事に縛られる必要はありません。", "evidence": "吸入薬のコンプライアンス向上", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗菌薬", "question": "「ニューキノロン系抗菌薬」の使用中に、日光に当たることで発疹が出る副作用を何と呼ぶか。", "options": ["日焼け", "光線過敏症", "多毛症", "蕁麻疹"], "correctAnswerIndex": 1, "explanation": "薬の成分が紫外線の影響で炎症を起こすため、長袖の着用などの遮光指導が必要です。", "evidence": "薬剤による光毒性アセスメント", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "去痰薬", "question": "「カルボシステイン（ムコダイン等）」は気管支炎だけでなく、耳鼻科領域のどの病気に広く使われるか。", "options": ["耳鳴り", "滲出性中耳炎や副鼻腔炎 (粘膜の修復を助けるため)", "難聴", "鼻血"], "correctAnswerIndex": 1, "explanation": "鼻水（膿）の粘りを取って排泄を促し、粘膜を正常にする働きが広く利用されています。", "evidence": "粘液修復薬の臨床応用", "reference": "看護roo!" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "テオフィリン", "question": "テオフィリン製剤の「相互作用」において、アルコールと一緒に摂取するとどうなるか。", "options": ["薬の効果が消える", "アルコールによりテオフィリンの副作用（興奮・不整脈等）が助長されるリスクがある", "酔いが冷める", "特になし"], "correctAnswerIndex": 1, "explanation": "中枢神経系への影響が重なり、予期せぬ中毒症状が出る可能性があるため避けるべきです。", "evidence": "アルコールと薬剤の併用リスク", "reference": "SafetyPlus" }
];

const updatedQuestions = [...questions, ...newQuestions];
fs.writeFileSync(questionsPath, JSON.stringify(updatedQuestions, null, 2), 'utf8');
console.log(`Successfully updated questions.json with Batch 13. New Total: ${updatedQuestions.length}`);
