const fs = require('fs');
const path = require('path');

const questionsPath = path.join(__dirname, 'src/data/questions.json');
const rawData = fs.readFileSync(questionsPath, 'utf8');
const questions = JSON.parse(rawData);

let currentId = Math.max(...questions.map(q => q.id), 0) + 1;

const newQuestions = [
    // ①呼吸器手技 (IDs series, 50 items)
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "吸引", "question": "気管吸引時に「低酸素血症」を認めた際、酸素投与以外で検討すべき手技調節はどれか。", "options": ["吸引圧を極限まで下げる、または吸引時間を短縮する", "カテーテルを太くする", "吸引回数を増やす", "特にない"], "correctAnswerIndex": 0, "explanation": "吸引圧が強すぎたり、時間が長すぎたりすると、肺内の酸素を奪いすぎてしまうため、設定の再検討が必要です。", "evidence": "酸素化を維持する吸引技術", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "酸素療法", "question": "「リザーバー付マスク」において、リザーバー内に酸素を貯める主な目的はどれか。", "options": ["マスクを重くするため", "吸気時に高い濃度の酸素（60-90%程度）を安定して送り込むため", "温めるため", "特になし"], "correctAnswerIndex": 1, "explanation": "通常のマスクよりも高い酸素濃度を必要とする患者に対し、予備の酸素を溜めておく役割を果たします。", "evidence": "高濃度酸素療法のデバイス管理", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "人工呼吸器", "question": "人工呼吸器の「分時換気量」とは何を計算したものか。", "options": ["1回換気量 × 呼吸数", "体重 ÷ 身長", "肺の重さ", "最高気道圧"], "correctAnswerIndex": 0, "explanation": "1分間に肺を通過する空気の総量であり、換気状態を評価する最も基本的な指標の一つです。", "evidence": "呼吸管理の生理学的指標", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "救急対応", "question": "「死戦期呼吸」を見逃して、胸骨圧迫を開始しないことで起こる致命的な結果は何か。", "options": ["患者が眠り続ける", "脳への血流が途絶え、蘇生後の脳機能障害や死亡を招く", "食欲がなくなる", "特になし"], "correctAnswerIndex": 1, "explanation": "死戦期呼吸は「呼吸をしている」と誤解されやすいですが、実質的には心停止状態であり、即時のCPRが必要です。", "evidence": "蘇生ガイドライン2020", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "モニタリング", "question": "パルスオキシメータの値が「末梢の冷え（血管収縮）」で測定不能な際に行う「温熱法」の効果はどれか。", "options": ["酸素を増やす", "血管を拡張させ、末梢血流を改善して測定を可能にする", "指を細くする", "特にない"], "correctAnswerIndex": 1, "explanation": "手を温めることで循環が回復し、正確な波形が得られるようになります。", "evidence": "モニタリングのトラブルシューティング", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "口腔ケア", "question": "人工呼吸器装着患者の口腔ケアにおける「保湿」の重要性は何か。", "options": ["唇を綺麗にするため", "乾燥による粘膜のひび割れ（出血・感染源）を防ぎ、自浄作用を助けるため", "味を良くするため", "喋りやすくするため"], "correctAnswerIndex": 1, "explanation": "挿管中は口呼吸になりやすく激しく乾燥するため、保湿ジェル等でのケアが欠かせません。", "evidence": "VAP予防と口腔ケア", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "ドレーン管理", "question": "胸腔ドレーンの排液が「乳白色（ミルク状）」になった際、疑われる重篤な合併症はどれか。", "options": ["順調な経過", "乳糜胸 (にゅうびきょう：リンパ液が漏れ出ている状態)", "牛乳の誤飲", "膿胸"], "correctAnswerIndex": 1, "explanation": "リンパ管を損傷し、脂肪分を含んだリンパ液が胸の中に溜まっているサインです。", "evidence": "ドレーン排液のアセスメント", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "その他", "question": "「パルスオキシメータ」を長時間同じ指に装着し続ける際、注意すべき合併症はどれか。", "options": ["指が伸びる", "圧迫による褥瘡（皮膚潰瘍）や低温熱傷", "指の色が白くなるだけ", "特にない"], "correctAnswerIndex": 1, "explanation": "センサーの圧迫や発熱により皮膚が傷つくことがあるため、定期的な装着部位の変更が必要です。", "evidence": "医療機器による皮膚トラブル予防", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "吸引", "question": "閉鎖式吸引システム（インライン吸引）の最大のメリットはどれか。", "options": ["安いから", "回路を開放せずに吸引できるため、PEEPの維持や感染防止に優れていること", "音が静かだから", "操作が複雑だから"], "correctAnswerIndex": 1, "explanation": "人工呼吸器の条件を維持したまま、かつ医療従事者への感染曝露も防げるシステムです。", "evidence": "閉鎖式吸引の実技と利点", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "①呼吸器手技", "subCategory": "酸素療法", "question": "酸素ボンベの主要な安全点検項目「ガス漏れ」の確認方法として適切なのはどれか。", "options": ["火を近づける", "耳を澄ませて「シュー」という音を聞き、パッキンの異常がないか確認する", "水に沈める", "特に何もしない"], "correctAnswerIndex": 1, "explanation": "高圧ガスの漏れは火災や窒息のリスクとなるため、日常的な聴取点検が必須です。", "evidence": "医療用ガスの安全管理基準", "reference": "SafetyPlus" },

    // ②疾患観察 (IDs series, 50 items)
    { "id": currentId++, "category": "②疾患観察", "subCategory": "心不全", "question": "心不全患者における「むくみ（浮腫）」が、重力に従って足や背中に現れる性質を何と呼ぶか。", "options": ["特発性浮腫", "体位性浮腫（重力依存性浮腫）", "膠質浸透圧による浮腫", "不眠による浮腫"], "correctAnswerIndex": 1, "explanation": "歩いている時は足に、寝ている時は背中側に水分が溜まるのが心不全による浮腫の特徴です。", "evidence": "浮腫のアセスメントとケア", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "呼吸介助手技の「バイブレーション」の目的はどれか。", "options": ["患者を励ますため", "細かい振動を伝えることで、気壁にこびりついた痰を剥がしやすくするため", "冷やすため", "特になし"], "correctAnswerIndex": 1, "explanation": "呼気時に細かな振動を手から伝えることで、排痰を物理的に支援します。", "evidence": "呼吸理学療法の手技解説", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "COPD", "question": "COPD患者が「高カロリー・少量頻回」の食事を勧められる理由は何か。", "options": ["お腹がいっぱいになると息苦しくなる（横隔膜を圧迫する）のを防ぐため", "食べるのが遅いから", "太らせるため", "味が濃いから"], "correctAnswerIndex": 0, "explanation": "一度にたくさん食べると胃が膨らみ、肺を圧迫して呼吸を苦しくさせるため、小分けにして摂取します。", "evidence": "呼吸器疾患の栄養管理", "reference": "看護roo!" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "肺炎", "question": "「マイコプラズマ肺炎」の特徴的な身体所見はどれか。", "options": ["激しい膿のような痰", "比較的元気なのに激しい「乾いた咳」が長く続く", "血圧上昇", "多尿"], "correctAnswerIndex": 1, "explanation": "若い人によく見られ、頑固な空咳（乾性咳嗽）が主症状となるのが特徴です。", "evidence": "非定型肺炎の診療指針", "reference": "看護roo!" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "気胸", "question": "気胸の治療である「胸腔ドレナージ」の際、水封室の液面が呼吸に合わせて上下に動く現象を何と呼ぶか。", "options": ["逆流", "呼吸性変動", "エアリーク", "故障"], "correctAnswerIndex": 1, "explanation": "ドレーンが正しく胸腔内にあり、疎通性が確保されていることを示す正常なサインです。", "evidence": "ドレーン看視のチェックポイント", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "疾患管理", "question": "「肺血栓塞栓症」のリスクを高める生活習慣として注意が必要なのはどれか。", "options": ["読書", "喫煙（特にピル服用中など）や長時間の不動（座りっぱなし）", "歌唱", "野菜中心の食事"], "correctAnswerIndex": 1, "explanation": "血液がドロドロになりやすく、かつ血流が滞る環境は血栓形成の最大のリスク因子です。", "evidence": "ライフスタイルと血栓症", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "意識評価指標の「JCS 10」とは、どのような状態か。", "options": ["普通の覚醒", "普通の呼びかけで容易に開眼する状態", "痛みでようやく開眼する状態", "何をやっても開眼しない"], "correctAnswerIndex": 1, "explanation": "1桁(1,2,3)は覚醒している、2桁(10,20,30)は刺激で覚醒する、3桁(100,200,300)は覚醒しない、の分類です。", "evidence": "JCSによる意識評価の徹底", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "その他", "question": "患者が「冷や汗・生あくび・顔面蒼白」を訴えた際、看護師が真っ先に疑う緊急事態はどれか。", "options": ["退屈", "ショックの初期症状、または迷走神経反射", "空腹", "睡眠不足"], "correctAnswerIndex": 1, "explanation": "これらはバイタル変化が現れる前の急変の「前兆（サイン）」として非常に重要です。", "evidence": "急変の予兆（Killer Symptoms）", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "フィジカルアセスメント", "question": "呼吸介助中に「皮下気腫」が出現・悪化した場合の対応として最も適切なのはどれか。", "options": ["より強く圧迫する", "直ちに中止し、気胸の悪化を疑って医師へ報告・レントゲンを依頼する", "マッサージを続ける", "無視する"], "correctAnswerIndex": 1, "explanation": "手技による圧変化で肺のリークが皮膚の下に広がっている可能性があり、重大な悪化サインです。", "evidence": "呼吸理学療法の安全管理", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "②疾患観察", "subCategory": "疾患管理", "question": "高齢患者が「いつもよりぼーっとしている（傾眠）」際、肺炎以外に真っ先に確認すべき血液関連の数値はどれか。", "options": ["コレステロール", "血糖値 (低血糖の可能性)", "尿酸値", "ビタミン"], "correctAnswerIndex": 1, "explanation": "低血糖は緊急の処置を要し、かつ早期に改善可能な「意識障害」の重要原因です。", "evidence": "意識障害の鑑別診断 (AIUEOTIPS)", "reference": "SafetyPlus" },

    // ③薬剤知識 (IDs series, 50 items)
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "吸入薬", "question": "吸入薬デバイス「ハンディヘラー（スピリーバ等）」を使用する際、カプセルを装填した後にボタンを「1回だけ」押すのはなぜか。", "options": ["ボタンを掃除するため", "カプセルに針を通して薬剤を吸えるようにするため（何度も押すとカプセルが壊れる）", "音を聞くため", "特になし"], "correctAnswerIndex": 1, "explanation": "ボタンを押すことで針がカプセルに穴を開けます。何度も押すとカプセルが粉々になり、不適切な吸入になります。", "evidence": "ハンディヘラーの操作手順", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗菌薬", "question": "「グリコペプチド系抗菌薬（バンコマイシン等）」を長期使用する際、特にモニタリングすべき数値はどれか。", "options": ["血中濃度 (副作用と効果の確認)", "髪の毛の太さ", "体重増加", "視力"], "correctAnswerIndex": 0, "explanation": "血中濃度が高すぎると腎障害や耳毒性のリスクがあり、低すぎると効果が出ないため、TDM（血中濃度モニタリング）が必須です。", "evidence": "TDMが必要な薬剤管理", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗凝固薬", "question": "「エドキサバン（リクシアナ）」などのDOACを服用している患者が、歯科治療や手術を受ける際の注意点はどれか。", "options": ["特にない", "出血が止まりにくい可能性があるため、休薬の必要性を主治医に確認する", "歯を抜かない", "薬を倍飲む"], "correctAnswerIndex": 1, "explanation": "侵襲を伴う処置では出血リスクを評価し、適切な対応が必要です。", "evidence": "周術期抗凝固療法", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "ステロイド薬", "question": "ステロイド薬の副作用「野牛肩（バッファローハンプ）」が起きるメカニズムはどれか。", "options": ["筋肉痛", "脂肪の異常な沈着（中心性肥満の一種）", "骨の変形", "特にない"], "correctAnswerIndex": 1, "explanation": "ステロイドの代謝作用により、頸部後方に脂肪が蓄積する独特の副作用です。", "evidence": "ステロイド代謝異常症候群", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "鎮静薬", "question": "モルヒネ使用中に起こる「吐き気」を予防するために、併用が検討される薬剤の種類はどれか。", "options": ["眠眠打破", "制吐薬 (吐き気どめ)", "下剤", "ビタミン剤"], "correctAnswerIndex": 1, "explanation": "使い始めに出やすい吐き気を予防的にコントロールすることで、治療の継続性を高めます。", "evidence": "オピオイド使用の標準ケア", "reference": "看護roo!" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "インスリン", "question": "インスリンの「混濁（白濁）」タイプの薬剤を使用する直前に行わなければならない動作はどれか。", "options": ["激しく振る", "手の中でゆっくり転がすようにして、均一に混ぜる", "温める", "特になし"], "correctAnswerIndex": 1, "explanation": "激しく振ると気泡が混じり正確な量を量り取れないため、穏やかに撹拌します。", "evidence": "インスリン製剤の取扱い", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "吸入薬", "question": "吸入ステロイド薬の開始後、効果が出るまでの期間として患者に説明すべき目安はどれか。", "options": ["吸って1秒後", "毎日続けて、数日から2週間程度で徐々に効果が現れる", "一生出ない", "1年後"], "correctAnswerIndex": 1, "explanation": "即効性を期待する薬ではなく、炎症をじわじわ抑える「管理薬」であることを理解してもらう必要があります。", "evidence": "喘息コントロールの基礎知識", "reference": "Nursing Skills" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "抗菌薬", "question": "特定の抗菌薬で「不快な金属味」がすると訴える患者に対して、看護師が確認すべき副作用はどれか。", "options": ["味覚異常", "心不全", "不眠", "食欲不振"], "correctAnswerIndex": 0, "explanation": "マクロライド系やキノロン系などの一部の抗菌薬では、特徴的な味覚の変化を感じることがあります。", "evidence": "薬剤の有害事象と看護", "reference": "SafetyPlus" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "去痰薬", "question": "痰を分解する酵素を含む「プロナーゼ（プロナミド等）」の飲用上の注意点はどれか。", "options": ["水以外で飲んではいけない", "特になし", "薬が溶けやすいよう温かいお湯で飲むとより効果的（諸説あり）", "冷たい水だけ"], "correctAnswerIndex": 2, "explanation": "酵素の活性を促し、喉の奥の痰を分解しやすくするために、適切な温度での内服が推奨されることがあります。", "evidence": "薬剤指導の実務", "reference": "看護roo!" },
    { "id": currentId++, "category": "③薬剤知識", "subCategory": "テオフィリン", "question": "テオフィリン製剤の投与中に「喫煙」を始めた、あるいは止めた場合に考慮すべきことは何か。", "options": ["特に変わらない", "喫煙は薬の代謝を速めるため、喫煙状況の変化により血中濃度が激しく変動する", "禁欲", "特になし"], "correctAnswerIndex": 1, "explanation": "タバコの成分（多環芳香族炭化水素）が薬剤の代謝酵素を活性化させてしまうため、用量調節が密接に関連します。", "evidence": "薬物代謝と喫煙の相互作用", "reference": "SafetyPlus" }
];

const updatedQuestions = [...questions, ...newQuestions];
fs.writeFileSync(questionsPath, JSON.stringify(updatedQuestions, null, 2), 'utf8');
console.log(`Successfully updated questions.json with Batch 12. New Total: ${updatedQuestions.length}`);
